package com.joel.domain

enum class CountryCode(val code: String, val countryName: String) {
    AFGHANISTAN("af", "Afghanistan"),
    ALBANIA("al", "Albania"),
    ALGERIA("dz", "Algeria"),
    AMERICAN_SAMOA("as", "American Samoa"),
    ANGUILLA("ai", "Anguilla"),
    AUSTRALIA("au", "Australia"),
    AUSTRIA("at", "Austria"),
    BAHAMAS("bs", "Bahamas"),
    BAHRAIN("bh", "Bahrain"),
    BANGLADESH("bd", "Bangladesh"),
    BARBADOS("bb", "Barbados"),
    BELARUS("by", "Belarus"),
    BELGIUM("be", "Belgium"),
    BELIZE("bz", "Belize"),
    BENIN("bj", "Benin"),
    BERMUDA("bm", "Bermuda"),
    BHUTAN("bt", "Bhutan"),
    BOSNIA_AND_HERZEGOVINA("ba", "Bosnia and Herzegovina"),
    BOUVET_ISLAND("bv", "Bouvet Island"),
    BRAZIL("br", "Brazil"),
    BRITISH_INDIAN_OCEAN_TERRITORY("io", "British Indian Ocean Territory"),
    BRUNEI_DARUSSALAM("bn", "Brunei Darussalam"),
    BULGARIA("bg", "Bulgaria"),
    BURKINA_FASO("bf", "Burkina Faso"),
    BURUNDI("bi", "Burundi"),
    CAMBODIA("kh", "Cambodia"),
    CAMEROON("cm", "Cameroon"),
    CANADA("ca", "Canada"),
    CAPE_VERDE("cv", "Cape Verde"),
    CENTRAL_AFRICAN_REPUBLIC("cf", "Central African Republic"),
    CHILE("cl", "Chile"),
    CHINA("cn", "China"),
    COLOMBIA("co", "Colombia"),
    COMOROS("km", "Comoros"),
    CONGO_DEMOCRATIC_REPUBLIC("cd", "Congo, Democratic Republic of the"),
    CONGO_REPUBLIC("cg", "Congo, Republic of the"),
    COSTA_RICA("cr", "Costa Rica"),
    COTE_DIVOIRE("ci", "Cote D'ivoire"),
    CROATIA("hr", "Croatia"),
    CUBA("cu", "Cuba"),
    CYPRUS("cy", "Cyprus"),
    CZECH_REPUBLIC("cz", "Czech Republic"),
    DENMARK("dk", "Denmark"),
    DJIBOUTI("dj", "Djibouti"),
    DOMINICAN_REPUBLIC("do", "Dominican Republic"),
    ECUADOR("ec", "Ecuador"),
    EGYPT("eg", "Egypt"),
    EL_SALVADOR("sv", "El Salvador"),
    ERITREA("er", "Eritrea"),
    ETHIOPIA("et", "Ethiopia"),
    EUROPE("eu", "Europe"),
    FIJI("fj", "Fiji"),
    FINLAND("fi", "Finland"),
    FRANCE("fr", "France"),
    FRENCH_GUIANA("gf", "French Guiana"),
    FRENCH_POLYNESIA("pf", "French Polynesia"),
    GAMBIA("gm", "Gambia"),
    GERMANY("de", "Germany"),
    GHANA("gh", "Ghana"),
    GREECE("gr", "Greece"),
    GUATEMALA("gt", "Guatemala"),
    GUINEA("gn", "Guinea"),
    GUYANA("gy", "Guyana"),
    HONDURAS("hn", "Honduras"),
    HONG_KONG("hk", "Hong Kong"),
    HUNGARY("hu", "Hungary"),
    ICELAND("is", "Iceland"),
    INDIA("in", "India"),
    INDONESIA("id", "Indonesia"),
    IRAN("ir", "Iran"),
    IRAQ("iq", "Iraq"),
    IRELAND("ie", "Ireland"),
    ISRAEL("il", "Israel"),
    ITALY("it", "Italy"),
    JAPAN("jp", "Japan"),
    JORDAN("jo", "Jordan"),
    KAZAKHSTAN("kz", "Kazakhstan"),
    KENYA("ke", "Kenya"),
    KUWAIT("kw", "Kuwait"),
    LAOS("la", "Laos"),
    LATVIA("lv", "Latvia"),
    LEBANON("lb", "Lebanon"),
    LESOTHO("ls", "Lesotho"),
    LIBERIA("lr", "Liberia"),
    LIECHTENSTEIN("li", "Liechtenstein"),
    LITHUANIA("lt", "Lithuania"),
    LUXEMBOURG("lu", "Luxembourg"),
    MACEDONIA("mk", "Macedonia"),
    MADAGASCAR("mg", "Madagascar"),
    MALAWI("mw", "Malawi"),
    MALAYSIA("my", "Malaysia"),
    MALDIVES("mv", "Maldives"),
    MALI("ml", "Mali"),
    MALTA("mt", "Malta"),
    MAURITANIA("mr", "Mauritania"),
    MAURITIUS("mu", "Mauritius"),
    MEXICO("mx", "Mexico"),
    MICRONESIA("fm", "Micronesia, Federated States of"),
    MOLDOVA("md", "Moldova"),
    MONACO("mc", "Monaco"),
    MONTENEGRO("me", "Montenegro"),
    MONTSERRAT("ms", "Montserrat"),
    MOROCCO("ma", "Morocco"),
    MYANMAR("mm", "Myanmar"),
    NAMIBIA("na", "Namibia"),
    NEPAL("np", "Nepal"),
    NETHERLANDS("nl", "Netherlands"),
    NEW_ZEALAND("nz", "New Zealand"),
    NIGER("ne", "Niger"),
    NIGERIA("ng", "Nigeria"),
    NORTH_KOREA("kp", "North Korea"),
    NORWAY("no", "Norway"),
    OMAN("om", "Oman"),
    PAKISTAN("pk", "Pakistan"),
    PALESTINIAN_TERRITORY("ps", "Palestinian Territory"),
    PARAGUAY("py", "Paraguay"),
    PERU("pe", "Peru"),
    PHILIPPINES("ph", "Philippines"),
    POLAND("pl", "Poland"),
    PORTUGAL("pt", "Portugal"),
    QATAR("qa", "Qatar"),
    ROMANIA("ro", "Romania"),
    RUSSIA("ru", "Russia"),
    RWANDA("rw", "Rwanda"),
    SAINT_KITTS_AND_NEVIS("kn", "Saint Kitts and Nevis"),
    SAINT_VINCENT_AND_THE_GRENADINES("vc", "Saint Vincent and the Grenadines"),
    SAN_MARINO("sm", "San Marino"),
    SAUDI_ARABIA("sa", "Saudi Arabia"),
    SENEGAL("sn", "Senegal"),
    SERBIA("rs", "Serbia"),
    SEYCHELLES("sc", "Seychelles"),
    SIERRA_LEONE("sl", "Sierra Leone"),
    SINGAPORE("sg", "Singapore"),
    SLOVAKIA("sk", "Slovakia"),
    SLOVENIA("si", "Slovenia"),
    SOLOMON_ISLANDS("sb", "Solomon Islands"),
    SOMALIA("so", "Somalia"),
    SOUTH_AFRICA("za", "South Africa"),
    SOUTH_KOREA("kr", "South Korea"),
    SPAIN("es", "Spain"),
    SRI_LANKA("lk", "Sri Lanka"),
    SURINAME("sr", "Suriname"),
    SWAZILAND("sz", "Swaziland"),
    SWEDEN("se", "Sweden"),
    SWITZERLAND("ch", "Switzerland"),
    SYRIA("sy", "Syria"),
    TAIWAN("tw", "Taiwan"),
    TAJIKISTAN("tj", "Tajikistan"),
    THAILAND("th", "Thailand"),
    TIMOR_LESTE("tl", "Timor-Leste"),
    TOGO("tg", "Togo"),
    TONGA("to", "Tonga"),
    TRINIDAD_AND_TOBAGO("tt", "Trinidad and Tobago"),
    TURKEY("tr", "Turkey"),
    TUVALU("tv", "Tuvalu"),
    UKRAINE("ua", "Ukraine"),
    UGANDA("ug", "Uganda"),
    UNITED_ARAB_EMIRATES("ae", "United Arab Emirates"),
    UNITED_KINGDOM("gb", "United Kingdom"),
    UNITED_STATES_OF_AMERICA("us", "United States of America"),
    URUGUAY("uy", "Uruguay"),
    UZBEKISTAN("uz", "Uzbekistan"),
    VANUATU("vu", "Vanuatu"),
    ZAMBIA("zm", "Zambia");

    companion object {
        fun fromCode(code: String): CountryCode? {
            return entries.find { it.code == code }
        }

        fun fromCountryName(countryName: String): CountryCode? {
            return entries.find { it.countryName == countryName }
        }
    }
}




